CC = gcc
CFLAGS = -O2 -Wall
LIBS = -lext2fs -lcom_err -lntfs-3g

all: dfind

dfind: main.c util.c live.c fs_ext.c fs_ntfs.c dfind.h
	$(CC) $(CFLAGS) -o dfind main.c util.c live.c fs_ext.c fs_ntfs.c $(LIBS)

clean:
	rm -f dfind
